from carta import Carta

cartas = [
    Carta("Caballero", "Tropa", 3, 1),
    Carta("Arqueras", "Tropa", 3, 1),
    Carta("Gigante", "Tropa", 5, 1),
    Carta("Bola de Fuego", "Hechizo", 4, 1),
    Carta("Descarga", "Hechizo", 2, 1),
    Carta("Mosquetera", "Tropa", 4, 1),
    Carta("Bebé Dragón", "Tropa", 4, 1),
    Carta("P.E.K.K.A", "Tropa", 7, 1),
    Carta("Príncipe", "Tropa", 5, 1),
    Carta("Mini P.E.K.K.A", "Tropa", 4, 1),
    Carta("Ejército de Esqueletos", "Tropa", 3, 1),
    Carta("Bruja", "Tropa", 5, 1),
    Carta("Montapuercos", "Tropa", 4, 1),
    Carta("Esqueleto Gigante", "Tropa", 6, 1),
    Carta("Barril de Duendes", "Hechizo", 3, 1),
    Carta("Valquiria", "Tropa", 4, 1),
    Carta("Tesla", "Estructura", 4, 1),
    Carta("Cañón", "Estructura", 3, 1),
    Carta("Lanzarrocas", "Tropa", 5, 1),
    Carta("Verdugo", "Tropa", 5, 1),
    Carta("Leñador", "Tropa", 4, 1),
    Carta("Tornado", "Hechizo", 3, 1),
    Carta("Chispitas", "Tropa", 6, 1),
    Carta("Mago", "Tropa", 5, 1),
    Carta("Minero", "Tropa", 3, 1),
    Carta("Rayo", "Hechizo", 6, 1),
    Carta("Globo Bombástico", "Tropa", 5, 1),
    Carta("Mago Eléctrico", "Tropa", 4, 1),
    Carta("Dragón Infernal", "Tropa", 4, 1),
    Carta("Megacaballero", "Tropa", 7, 1),
    Carta("Bandida", "Tropa", 3, 1)
]
